<script setup>
import { ref } from 'vue';
import { Head, useForm } from '@inertiajs/vue3';
import Navbar from '@/Components/Navbar.vue';
import GlobalSearchModal from '@/Components/GlobalSearchModal.vue';
import { 
  CheckIcon, 
  BuildingOfficeIcon,
  SparklesIcon,
  PlusIcon,
  TrashIcon,
  XMarkIcon,
  ArrowPathIcon
} from '@heroicons/vue/24/outline';

const props = defineProps({
  navigationItems: Array,
  businessSettings: Object,
  availableIcons: Array,
});

const isSearchOpen = ref(false);
const isAddModalOpen = ref(false);

const newItem = ref({
  key: '',
  label: '',
  route: '/',
  icon: 'HomeIcon',
  display_order: (props.navigationItems?.length || 0) + 1,
  is_enabled: true
});

const form = useForm({
  business_name: props.businessSettings.business_name || 'JRV CRM',
  business_icon: props.businessSettings.business_icon || '♥',
  brand_color: props.businessSettings.brand_color || 'red',
  items: props.navigationItems.map(item => ({ ...item })),
  deleted_ids: []
});

const generateKey = (label) => {
  return label.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
};

const onLabelInput = () => {
  if (!newItem.value.key || newItem.value.isKeyAutoGenerated) {
    newItem.value.key = generateKey(newItem.value.label);
    newItem.value.isKeyAutoGenerated = true;
  }
};

const presets = [
  { label: 'App Dashboard', key: 'app', route: '/app', icon: 'HomeIcon' },
  { label: 'Dashboard', key: 'dashboard', route: '/dashboard', icon: 'ChartBarIcon' },
  { label: 'Enquiries / Leads', key: 'leads', route: '/leads', icon: 'UserIcon' },
  { label: 'Contacts', key: 'contacts', route: '/contacts', icon: 'UserIcon' },
  { label: 'Staff Recruitment', key: 'staff_recruit', route: '/staff-recruitment', icon: 'BriefcaseIcon' },
  { label: 'Data Import Hub', key: 'data_import', route: '/data-import', icon: 'TableCellsIcon' },
  { label: 'Staff Management', key: 'staff_management', route: '/employee-management', icon: 'UserGroupIcon' },
  { label: 'Task Dashboard', key: 'task_dashboard', route: '/task-dashboard', icon: 'ClipboardDocumentListIcon' },
];

const applyPreset = (preset) => {
  newItem.value.label = preset.label;
  newItem.value.key = preset.key;
  newItem.value.route = preset.route;
  newItem.value.icon = preset.icon;
  newItem.value.isKeyAutoGenerated = false;
};

const openAddModal = () => {
  newItem.value = {
    key: '',
    label: '',
    route: '/',
    icon: 'HomeIcon',
    display_order: form.items.length + 1,
    is_enabled: true,
    isKeyAutoGenerated: true
  };
  isAddModalOpen.value = true;
};

const addMenuItem = () => {
  if (!newItem.value.label || !newItem.value.key) return;

  form.items.push({
    id: null,
    key: newItem.value.key,
    label: newItem.value.label,
    route: newItem.value.route || '/',
    icon: newItem.value.icon || 'HomeIcon',
    display_order: parseInt(newItem.value.display_order) || form.items.length + 1,
    is_enabled: newItem.value.is_enabled
  });

  isAddModalOpen.value = false;
};

const removeMenuItem = (index) => {
  const item = form.items[index];
  if (item && item.id) {
    form.deleted_ids.push(item.id);
  }
  form.items.splice(index, 1);
};

const saveChanges = () => {
  form.post('/tenant/settings/navigation', {
    preserveScroll: true,
  });
};
</script>

<template>
  <Head title="Customize Business Identity & Navigation Icons - CRM" />

  <div class="min-h-screen bg-slate-100 flex font-sans text-slate-900">
    <Navbar @open-search="isSearchOpen = true" />

    <main class="flex-1 p-8 space-y-8 overflow-y-auto min-w-0 max-w-7xl mx-auto w-full">
      <!-- Header Bar -->
      <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-slate-200 pb-6">
        <div>
          <h1 class="text-3xl font-extrabold tracking-tight text-slate-900">
            Customize Business Identity & Menu Icons
          </h1>
          <p class="text-slate-500 text-sm mt-1">Change your business name, logo icon, brand accent color, and add or remove navigation menu options.</p>
        </div>

        <div class="flex items-center gap-3">
          <button 
            @click="openAddModal"
            type="button"
            class="px-4 py-2.5 bg-slate-800 hover:bg-slate-900 text-white text-sm font-bold rounded-xl shadow-xs flex items-center gap-2 transition-all"
          >
            <PlusIcon class="w-5 h-5 stroke-[2.5]" />
            <span>Add Menu Option</span>
          </button>

          <button 
            @click="saveChanges"
            :disabled="form.processing"
            class="px-6 py-2.5 bg-red-600 hover:bg-red-700 text-white text-sm font-bold rounded-xl shadow-md flex items-center gap-2 transition-all disabled:opacity-50"
          >
            <CheckIcon class="w-5 h-5 stroke-[3]" />
            <span>Save All Customizations</span>
          </button>
        </div>
      </div>

      <!-- SECTION 1: Business Identity & Logo Customizer -->
      <div class="bg-white border border-slate-200 rounded-3xl p-6 shadow-xs space-y-6">
        <div class="flex items-center gap-2 pb-3 border-b border-slate-100">
          <BuildingOfficeIcon class="w-5 h-5 text-red-600" />
          <h2 class="text-base font-bold text-slate-900">Business Identity & Logo Customization</h2>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-3 gap-6 items-center">
          <!-- Business Name Input -->
          <div class="space-y-1">
            <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider">Business Name</label>
            <input 
              v-model="form.business_name" 
              type="text" 
              placeholder="e.g. JRV CRM or Acme Global"
              required
              class="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold text-slate-900 focus:outline-none focus:border-red-500"
            />
          </div>

          <!-- Business Logo Symbol / Icon -->
          <div class="space-y-1">
            <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider">Logo Symbol / Icon</label>
            <div class="flex items-center gap-3">
              <input 
                v-model="form.business_icon" 
                type="text" 
                placeholder="♥, C, ⚡, 🏢"
                required
                class="w-24 bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-center text-lg font-black text-slate-900 focus:outline-none focus:border-red-500"
              />
              <div class="w-10 h-10 bg-red-600 rounded-xl flex items-center justify-center text-white font-black text-xl shadow-md">
                {{ form.business_icon }}
              </div>
            </div>
          </div>

          <!-- Brand Accent Color Selection -->
          <div class="space-y-1">
            <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider">Brand Theme Accent</label>
            <select v-model="form.brand_color" class="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-xs font-bold text-slate-800 focus:outline-none focus:border-red-500">
              <option value="red">Red (Default)</option>
              <option value="indigo">Indigo</option>
              <option value="emerald">Emerald</option>
              <option value="amber">Amber Gold</option>
            </select>
          </div>
        </div>
      </div>

      <!-- SECTION 2: Navigation Options & Icon Customizer -->
      <div class="bg-white border border-slate-200 rounded-3xl p-6 shadow-xs space-y-6">
        <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 pb-3 border-b border-slate-100">
          <div class="flex items-center gap-2">
            <SparklesIcon class="w-5 h-5 text-red-600" />
            <h2 class="text-base font-bold text-slate-900">Navigation Options & Menu Icons Customization</h2>
            <span class="text-xs font-extrabold px-2.5 py-0.5 bg-slate-100 text-slate-600 rounded-full">
              {{ form.items.length }} Items
            </span>
          </div>

          <button 
            @click="openAddModal"
            type="button"
            class="inline-flex items-center gap-1.5 text-xs font-bold text-red-600 hover:text-red-700 hover:underline"
          >
            <PlusIcon class="w-4 h-4 stroke-[3]" />
            <span>Add New Menu Option</span>
          </button>
        </div>

        <div v-if="form.items.length === 0" class="py-12 text-center space-y-3">
          <p class="text-slate-500 text-sm font-medium">No navigation items configured. Click below to create one!</p>
          <button 
            @click="openAddModal"
            type="button"
            class="px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-xs font-bold rounded-xl"
          >
            + Add Menu Option
          </button>
        </div>

        <div v-else class="divide-y divide-slate-100">
          <div 
            v-for="(item, index) in form.items" 
            :key="item.id || index"
            class="py-4 grid grid-cols-1 sm:grid-cols-12 gap-3 items-center"
          >
            <!-- Order Input -->
            <div class="sm:col-span-1 text-center">
              <label class="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Order</label>
              <input 
                v-model="item.display_order" 
                type="number" 
                class="w-12 bg-slate-50 border border-slate-300 rounded-lg text-center text-xs font-bold py-1.5 focus:outline-none focus:border-red-500"
              />
            </div>

            <!-- Key Identifier -->
            <div class="sm:col-span-2">
              <label class="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Key</label>
              <input 
                v-model="item.key" 
                type="text" 
                required
                class="w-full bg-slate-50 border border-slate-300 rounded-xl px-2.5 py-1.5 text-xs font-mono font-bold text-slate-700 focus:outline-none focus:border-red-500"
              />
            </div>

            <!-- Custom Label Input -->
            <div class="sm:col-span-3">
              <label class="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Option Name</label>
              <input 
                v-model="item.label" 
                type="text" 
                required
                class="w-full bg-white border border-slate-300 rounded-xl px-3 py-1.5 text-xs font-bold text-slate-900 focus:outline-none focus:border-red-500"
              />
            </div>

            <!-- Route / Link Input -->
            <div class="sm:col-span-2">
              <label class="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Route / Link</label>
              <input 
                v-model="item.route" 
                type="text" 
                required
                placeholder="/"
                class="w-full bg-white border border-slate-300 rounded-xl px-2.5 py-1.5 text-xs font-medium text-slate-700 focus:outline-none focus:border-red-500"
              />
            </div>

            <!-- Icon Selector Dropdown -->
            <div class="sm:col-span-2">
              <label class="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Menu Icon</label>
              <select v-model="item.icon" class="w-full bg-white border border-slate-300 rounded-xl px-2.5 py-1.5 text-xs font-bold text-slate-700 focus:outline-none focus:border-red-500">
                <option v-for="iconName in availableIcons" :key="iconName" :value="iconName">
                  {{ iconName }}
                </option>
              </select>
            </div>

            <!-- Enabled Switch & Delete Action -->
            <div class="sm:col-span-2 flex items-center justify-end gap-3">
              <div class="flex items-center gap-1.5">
                <span class="text-[11px] font-bold text-slate-500">{{ item.is_enabled ? 'Active' : 'Off' }}</span>
                <button 
                  type="button"
                  @click="item.is_enabled = !item.is_enabled"
                  :class="[
                    'w-9 h-5 rounded-full p-0.5 transition-colors duration-200 ease-in-out',
                    item.is_enabled ? 'bg-red-600' : 'bg-slate-300'
                  ]"
                >
                  <div :class="[
                    'w-4 h-4 rounded-full bg-white shadow-xs transition-transform duration-200 ease-in-out',
                    item.is_enabled ? 'translate-x-4' : 'translate-x-0'
                  ]"></div>
                </button>
              </div>

              <!-- Delete / Remove Menu Button -->
              <button 
                type="button"
                @click="removeMenuItem(index)"
                title="Remove Menu Option"
                class="p-1.5 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
              >
                <TrashIcon class="w-4 h-4 stroke-[2]" />
              </button>
            </div>
          </div>
        </div>

        <div class="pt-4 border-t border-slate-100 flex items-center justify-between">
          <button 
            @click="openAddModal"
            type="button"
            class="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold rounded-xl flex items-center gap-1.5 transition-all"
          >
            <PlusIcon class="w-4 h-4 stroke-[2.5]" />
            <span>Add Another Menu Item</span>
          </button>

          <button 
            @click="saveChanges"
            :disabled="form.processing"
            class="px-6 py-2.5 bg-red-600 hover:bg-red-700 text-white text-xs font-bold rounded-xl shadow-md transition-all disabled:opacity-50"
          >
            Save All Customizations
          </button>
        </div>
      </div>
    </main>

    <!-- Modal: Add New Menu Option -->
    <div v-if="isAddModalOpen" class="fixed inset-0 z-50 overflow-y-auto p-4 flex items-center justify-center bg-slate-900/60 backdrop-blur-xs">
      <div class="bg-white rounded-3xl max-w-md w-full p-6 shadow-2xl space-y-6 relative border border-slate-100 max-h-[90vh] overflow-y-auto my-auto">
        <div class="flex items-center justify-between border-b border-slate-100 pb-4 sticky top-0 bg-white z-10">
          <div class="flex items-center gap-2">
            <PlusIcon class="w-5 h-5 text-red-600 stroke-[3]" />
            <h3 class="text-lg font-extrabold text-slate-900">Add New Navigation Option</h3>
          </div>
          <button @click="isAddModalOpen = false" class="text-slate-400 hover:text-slate-600 p-1 rounded-lg">
            <XMarkIcon class="w-5 h-5 stroke-[2.5]" />
          </button>
        </div>

        <div class="space-y-1.5 pb-2 border-b border-slate-100">
          <label class="block text-[11px] font-extrabold uppercase tracking-wider text-slate-500">⚡ Quick Add System Presets</label>
          <div class="flex flex-wrap gap-1.5">
            <button 
              v-for="preset in presets"
              :key="preset.key"
              type="button"
              @click="applyPreset(preset)"
              class="px-2.5 py-1 bg-red-50 hover:bg-red-100 border border-red-200 rounded-xl text-[11px] font-bold text-red-700 transition-all shadow-2xs flex items-center gap-1 cursor-pointer"
            >
              <span>+ {{ preset.label }}</span>
              <span class="text-[9px] text-red-400 font-mono">({{ preset.route }})</span>
            </button>
          </div>
        </div>

        <form @submit.prevent="addMenuItem" class="space-y-4">
          <div>
            <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Option Name *</label>
            <input 
              v-model="newItem.label"
              @input="onLabelInput"
              type="text" 
              placeholder="e.g. Support Desk, Reports, Courses"
              required
              class="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold text-slate-900 focus:outline-none focus:border-red-500"
            />
          </div>

          <div>
            <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Key Identifier *</label>
            <input 
              v-model="newItem.key"
              @input="newItem.isKeyAutoGenerated = false"
              type="text" 
              placeholder="e.g. support_desk"
              required
              class="w-full bg-slate-50 border border-slate-300 rounded-xl px-4 py-2.5 text-xs font-mono font-bold text-slate-800 focus:outline-none focus:border-red-500"
            />
            <p class="text-[11px] text-slate-400 mt-1">Unique key identifier for internal routing & settings.</p>
          </div>

          <div>
            <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Route / Target Link URL *</label>
            <input 
              v-model="newItem.route"
              type="text" 
              placeholder="e.g. /support or https://..."
              required
              class="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-xs font-medium text-slate-800 focus:outline-none focus:border-red-500"
            />
          </div>

          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Menu Icon</label>
              <select v-model="newItem.icon" class="w-full bg-white border border-slate-300 rounded-xl px-3 py-2.5 text-xs font-bold text-slate-700 focus:outline-none focus:border-red-500">
                <option v-for="iconName in availableIcons" :key="iconName" :value="iconName">
                  {{ iconName }}
                </option>
              </select>
            </div>

            <div>
              <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">Display Order</label>
              <input 
                v-model="newItem.display_order"
                type="number"
                class="w-full bg-white border border-slate-300 rounded-xl px-3 py-2.5 text-xs font-bold text-slate-900 focus:outline-none focus:border-red-500"
              />
            </div>
          </div>

          <div class="flex items-center justify-between pt-2">
            <span class="text-xs font-bold text-slate-700">Initial Status</span>
            <button 
              type="button"
              @click="newItem.is_enabled = !newItem.is_enabled"
              :class="[
                'w-10 h-6 rounded-full p-1 transition-colors duration-200 ease-in-out flex items-center',
                newItem.is_enabled ? 'bg-red-600' : 'bg-slate-300'
              ]"
            >
              <div :class="[
                'w-4 h-4 rounded-full bg-white shadow-xs transition-transform duration-200 ease-in-out',
                newItem.is_enabled ? 'translate-x-4' : 'translate-x-0'
              ]"></div>
            </button>
          </div>

          <div class="pt-4 flex items-center justify-end gap-3 border-t border-slate-100">
            <button 
              type="button" 
              @click="isAddModalOpen = false" 
              class="px-4 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100 rounded-xl"
            >
              Cancel
            </button>
            <button 
              type="submit" 
              class="px-5 py-2 bg-red-600 hover:bg-red-700 text-white text-xs font-bold rounded-xl shadow-md"
            >
              Add to Navigation List
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- Modals -->
    <GlobalSearchModal :is-open="isSearchOpen" @close="isSearchOpen = false" />
  </div>
</template>
